---
- name: Extract wordpress
  become: yes
  unarchive:
    src: http://wordpress.org/latest.tar.gz
    dest: /var/www/html/
    remote_src: yes

- name: Get wordpress salt
  local_action: command curl https://api.wordpress.org/secret-key/1.1/salt/
  register: "wp_salt"
  become: no
  become_method: sudo

- name: Copy wordpress configuration
  become: yes
  template: src=../templates/wp-config.php dest=/var/www/html/wordpress/wp-config.php

- name: Change wordpress owner
  file: path=/var/www/html/wordpress/ owner=www-data group=www-data state=directory recurse=yes

- name: Get wp-core
  get_url: url=https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar dest=/usr/local/bin/wp mode=a+x

- name: Configure site
  become_method: sudo
  shell: sudo -u vagrant -i -- wp core install --url={{ wp_core_url }} --title={{ wp_core_title }} --admin_user={{ wp_core_admin_user }} --admin_password={{ wp_core_admin_pass }} --admin_email={{ wp_core_admin_mail}} --path=/var/www/html/wordpress
