---
- name: Update repositories cache and install "bind9" package
  become: yes
  apt:
    name: bind9
    update_cache: yes

- name: Start bind9
  become: yes
  service:
    name: bind9
    state: started

- name: Bind9 Configuration File
  become: yes
  template:
    src: ../templates/named.conf.local
    dest: /etc/bind/named.conf.local

- name: Bind9 Zone Direct
  become: yes
  template:
    src: roles/bind9/templates/db.example.com
    dest: /var/cache/bind/db.example.com

- name: restart bind9
  become: yes
  service:
    name: bind9
    state: restarted
