---
- name: Install MariaDB & Python Dependencies
  become: yes
  apt:
    name: "{{ item }}"
  with_items:
    - mariadb-server
    - python-pip
    - python-dev
    - default-libmysqlclient-dev

- name: Start the MariaDB Service
  action: service name=mariadb state=started

- name: Install the MySQL-python through pip
  become: yes
  pip:
    name: "{{ item }}"
    state: forcereinstall
  with_items:
    - pip
    - MySQL-python

- name: Set root user password
  become: true
  become_user: root
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ mysql_root_password }}"
    priv: "*.*:ALL,GRANT"
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: copy .my.cnf file with root password credentials
  become: true
  become_user: root
  template: src=roles/mariadb/templates/.my.cnf dest=/root/.my.cnf owner=root mode=0600

- name: copy 50-server configuration - enable remote connections
  become: true
  copy: src=../templates/50-server.cnf dest=/etc/mysql/mariadb.conf.d/50-server.cnf

- name: create mariadb database
  become: true
  mysql_db:
    name: "{{ wp_db_name }}"
    state: present

- name: create mariadb user
  become: true
  become_user: root
  mysql_user:
    name: "{{ wp_db_user }}"
    host: "{{ item }}"
    password: "{{ wp_db_password }}"
    priv: "*.*:ALL,GRANT"
  with_items:
    - "{{ ansible_hostname }}"
    - "{{ int_nodo2 }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: restart mariadb
  become: yes
  service:
    name: mariadb
    state: restarted
