---
- name: Install php extensions
  become: yes
  apt:
    name: "{{ item }}"
  with_items:
    - php7.0
    - php7.0-mysql
    - php7.0-common
    - php7.0-readline
    - php7.0-fpm
    - php7.0-cli
    - php7.0-gd
    - php7.0-mcrypt
    - php7.0-curl
    - php7.0-mbstring
    - php7.0-opcache
    - php7.0-json

#- name: Restart Nginx
#  service:
#    name: nginx
#    state: restarted
- name: Restart nginx
  service: name=nginx state=restarted
  become: yes

- name: Restart php-fpm
  service: name=php7.0-fpm state=restarted
  become: yes
