---
- hosts: nodo2
  become: yes

  tasks:
  - name: Update
    apt:
      update_cache: yes
      cache_valid_time: 3600

  - name: Install Packages
    apt:
      name: "{{ item }}"
      update_cache: yes
    with_items:
      - nginx
      - php7.0-fpm
